# See the docs at https://github.com/geocoder-php/BazingaGeocoderBundle
bazinga_geocoder:
    providers:
        app:
            factory: 'Bazinga\GeocoderBundle\ProviderFactory\NominatimFactory'
            options:
                root_url: '%app.geocoder.root_url%'
                user_agent: 'Club Event Calendar https://github.com/silviokennecke/club-event-calendar'
